
publishers:

  # Node object_pos
  status_object_pos:
    topic: /affordances/status_object_pos
    queue_size: 1

  data_object_pos:
    topic: /affordances/data_object_pos
    queue_size: 1

  # Node person_object
  bounding_boxes:
    topic: /affordances/object_bounding_boxes
    queue_size: 1

  flag:
    topic: /affordances/flag
    queue_size: 1

  # Node person_pose
  status_person_pose:
    topic: /affordances/status_person_pose
    queue_size: 1

  data_person_pose:
    topic: /affordances/data_person_pose
    queue_size: 1

  # Node agent
  utility:
    topic: /affordances/utilities
    queue_size: 1

# MODE TRAIN VALUES
# (laptop) using 1, (sofa) lying down 2, (sofa) sitting 3, (bed) sleeping 4
# (cup) drinking 5, (refrigerator) using 6, exercising 7
train_object: "tvmonitor" # for tracking in train mode
valor_y: 7
# MODE PREDICTION VALUES
prediction_objects: # for tracking in prediction mode
  - refrigerator
  - cup
  - sofa
  - laptop
  - bed

detection_objects: # 55 objects
  - person
  - bicycle
  - car
  - motorbike
  - backpack
  - umbrella
  - handbag
  - tie
  - suitcase
  - skis
  - snowboard
  - sports ball
  - baseball bat
  - baseball glove
  - skateboard
  - tennis racket
  - bottle
  - wine glass
  - cup
  - fork
  - knife
  - spoon
  - bowl
  - banana
  - apple
  - sandwich
  - orange
  - broccoli
  - carrot
  - hot dog
  - pizza
  - donut
  - cake
  - chair
  - sofa
  - pottedplant
  - bed
  - diningtable
  - toilet
  - tvmonitor
  - laptop
  - mouse
  - remote
  - keyboard
  - cell phone
  - microwave
  - oven
  - toaster
  - sink
  - refrigerator
  - book
  - clock
  - vase
  - scissors
  - teddy bear
  - hair drier
  - toothbrush